// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/Cards-Circle": {
    params: {};
  };
  "/Horizontal-Tiles": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/Cards-Circle" | "/Horizontal-Tiles";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/cards-circle.tsx": {
    id: "routes/cards-circle";
    page: "/Cards-Circle";
  };
  "routes/horizontal-tiles.tsx": {
    id: "routes/horizontal-tiles";
    page: "/Horizontal-Tiles";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/cards-circle": typeof import("./app/routes/cards-circle.tsx");
  "routes/horizontal-tiles": typeof import("./app/routes/horizontal-tiles.tsx");
};