import { createRoot } from 'react-dom/client'
import './styles.css'
import { Logo } from '@pmndrs/branding'
import { App } from './App'

/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

// 提取静态样式常量，避免每次渲染创建新对象 (rendering-hoist-jsx)
const overlayStyle = {
  position: 'absolute',
  pointerEvents: 'none',
  top: 0,
  left: 0,
  width: '100vw',
  height: '100vh'
}

const dateStyle = { position: 'absolute', bottom: 40, right: 40, fontSize: '13px' }
const logoStyle = { position: 'absolute', bottom: 40, left: 40, width: 30 }
const hintStyle = { position: 'absolute', top: 40, left: 40, fontSize: '13px' }

function Root() {
  return (
    <>
      <App />
      <div style={overlayStyle}>
        <div style={dateStyle}>27/01/2026</div>
        <Logo style={logoStyle} />
        <a style={hintStyle} href="#">
          上下滚动试试看
        </a>
      </div>
    </>
  )
}

createRoot(document.getElementById('root')).render(<Root />)
